"""
honeypot.py — Honeypot / synthetic record detection for CipherRanker.

Provides:
  - is_honeypot(candidate: dict) -> (bool, str)
    Returns (True, reason) if the candidate is flagged as a honeypot.

Three independent checks:
  1. Literal marker strings in flattened text.
  2. Low character entropy (repetitive / garbage content).
  3. Implausibly large total claimed experience.
"""

import re
import math

# ---------------------------------------------------------------------------
# Literal markers — any of these in the lowercased text → instant flag
# ---------------------------------------------------------------------------
HONEYPOT_MARKERS = [
    "lorem ipsum",
    "test candidate",
    "honeypot",
    "dummy",
    "fake profile",
    "fake candidate",
    "placeholder",
    "sample data",
    "do not use",
    "ignore this",
    "generated by",
    "1234567890",
    "aaaaaaa",
    "xxxxxxx",
    "test user",
    "example candidate",
    "insert name here",
    "null null",
    "john doe",          # overly generic — flag lightly
    "jane doe",
]

# Regex for extracting explicit year counts ("5 years", "10+ years", etc.)
_YR_RE = re.compile(
    r"(\d+)\s*(?:\+|-)?\s*(?:\d+\s*)?year[s]?\s*(?:of\s+)?(?:experience)?",
    re.IGNORECASE,
)

# Entropy threshold — anything below this fraction of unique chars is suspicious
_ENTROPY_THRESHOLD = 0.02

# Maximum plausible total claimed years across all mentions
_MAX_PLAUSIBLE_YEARS = 80


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _flatten(candidate: dict) -> str:
    """Flatten all string values in a candidate dict into one lowercase blob."""
    parts: list[str] = []

    def _collect(obj):
        if isinstance(obj, str):
            parts.append(obj)
        elif isinstance(obj, list):
            for item in obj:
                _collect(item)
        elif isinstance(obj, dict):
            for v in obj.values():
                _collect(v)

    _collect(candidate)
    return " ".join(parts).lower()


def _char_entropy(text: str) -> float:
    """Fraction of unique characters — proxy for text diversity."""
    if len(text) == 0:
        return 1.0
    return len(set(text)) / len(text)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def is_honeypot(candidate: dict) -> tuple[bool, str]:
    """
    Check whether a candidate record is a synthetic / honeypot entry.

    Returns:
        (True,  reason_string) — if flagged
        (False, "")            — if clean
    """
    text = _flatten(candidate)

    # Check 1: literal markers
    for marker in HONEYPOT_MARKERS:
        if marker in text:
            return True, f"contains marker '{marker}'"

    # Check 2: low text entropy (repetitive / garbage)
    if len(text) > 80:
        if _char_entropy(text) < _ENTROPY_THRESHOLD:
            return True, "extremely low text entropy (repetitive / garbage content)"

    # Check 3: implausible total experience
    years = [int(m) for m in _YR_RE.findall(text)]
    if years and sum(years) > _MAX_PLAUSIBLE_YEARS:
        return True, (
            f"implausible claimed experience: {sum(years)} total years "
            f"({', '.join(str(y) for y in years)})"
        )

    return False, ""
