#!/usr/bin/env python3
"""
rank.py — Team Cipher candidate ranking pipeline.

Scores candidates from a JSONL (or JSONL.GZ) file using a 5-component
weighted scorer plus a behavioral multiplier and honeypot detector.
Outputs the top-100 ranked candidates to a CSV.

Usage:
    python rank.py --candidates ./candidates.jsonl --out ./team_cipher.csv
    python rank.py --candidates ./candidates.jsonl.gz --out ./team_cipher.csv
    python rank.py --candidates ./candidates.jsonl --out ./team_cipher.csv \\
                   --explain --workers 4 --w-skill 0.35 --w-exp 0.25
"""

import argparse
import csv
import gzip
import json
import math
import multiprocessing
import os
import re
import sys
import time
from pathlib import Path

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

PROGRESS_INTERVAL = 10_000
TOP_N             = 100
CHUNK_SIZE        = 5_000

# Default component weights (must sum to 1.0)
DEFAULT_WEIGHTS = {
    "skill"      : 0.30,
    "experience" : 0.25,
    "education"  : 0.15,
    "activity"   : 0.20,
    "diversity"  : 0.10,
}

# Behavioral multiplier bounds
BEH_MIN = 0.5
BEH_MAX = 1.5

# ---------------------------------------------------------------------------
# Keyword dictionaries
# ---------------------------------------------------------------------------

SKILL_KEYWORDS = {
    # Languages
    "python", "java", "javascript", "typescript", "c++", "c#", "go", "rust",
    "kotlin", "swift", "scala", "r", "julia", "sql", "bash", "perl", "ruby",
    # Frameworks / libraries
    "tensorflow", "pytorch", "keras", "scikit-learn", "sklearn", "pandas",
    "numpy", "spark", "hadoop", "kafka", "airflow", "dbt", "fastapi",
    "django", "flask", "react", "angular", "vue", "node", "spring", "rails",
    # Cloud / infra
    "aws", "gcp", "azure", "docker", "kubernetes", "k8s", "terraform",
    "ansible", "jenkins", "ci/cd", "github actions", "gitlab",
    # Data / ML
    "machine learning", "deep learning", "nlp", "cv", "computer vision",
    "reinforcement learning", "llm", "transformer", "bert", "gpt",
    "data engineering", "data science", "mlops", "feature engineering",
    "a/b testing", "statistics", "probability",
    # Databases
    "postgresql", "mysql", "mongodb", "redis", "elasticsearch", "cassandra",
    "bigquery", "snowflake", "redshift",
}

EXPERIENCE_KEYWORDS = {
    "senior": 3, "lead": 3, "principal": 4, "staff": 4, "director": 5,
    "vp": 5, "cto": 6, "architect": 4, "manager": 3, "head of": 4,
    "junior": 1, "intern": 0, "associate": 1, "mid": 2, "entry": 1,
}

_YR_PATTERN = re.compile(
    r"(\d+)\s*(?:\+|-)?\s*(?:\d+\s*)?year[s]?\s*(?:of\s+)?(?:experience)?",
    re.IGNORECASE
)

EDUCATION_LEVELS = {
    "phd": 1.0, "ph.d": 1.0, "doctorate": 1.0,
    "master": 0.75, "msc": 0.75, "ms ": 0.75, " ms,": 0.75, "mba": 0.70,
    "bachelor": 0.50, "bsc": 0.50, "b.sc": 0.50, "b.e": 0.50, "b.tech": 0.50,
    "associate": 0.25, "diploma": 0.20,
    "bootcamp": 0.15, "self-taught": 0.10, "online course": 0.10,
}

ACTIVITY_RECENCY_YEARS = {
    0: 1.0, 1: 0.9, 2: 0.75, 3: 0.55, 4: 0.35, 5: 0.20,
}

DIVERSITY_DOMAINS = [
    {"frontend", "ui", "ux", "design", "css", "html"},
    {"backend", "server", "api", "rest", "microservice"},
    {"data", "analytics", "bi", "reporting", "dashboard"},
    {"ml", "ai", "model", "inference", "training"},
    {"devops", "sre", "infrastructure", "cloud", "deployment"},
    {"mobile", "android", "ios", "flutter", "react native"},
    {"security", "cybersecurity", "pentest", "soc", "compliance"},
    {"blockchain", "web3", "smart contract", "defi"},
]

# ---------------------------------------------------------------------------
# Honeypot detection
# ---------------------------------------------------------------------------

HONEYPOT_FLAGS = [
    "lorem ipsum", "test candidate", "honeypot", "dummy", "fake profile",
    "1234567890", "aaaaaa", "xxxxxxx", "generated by", "placeholder",
    "sample data", "do not use", "ignore this",
]

def is_honeypot(text: str) -> tuple:
    lower = text.lower()
    for flag in HONEYPOT_FLAGS:
        if flag in lower:
            return True, f"contains marker '{flag}'"
    if len(text) > 100:
        unique_chars = len(set(text))
        entropy = unique_chars / max(len(text), 1)
        if entropy < 0.02:
            return True, "extremely low text entropy (repetitive content)"
    years = [int(m) for m in _YR_PATTERN.findall(lower)]
    if years and sum(years) > 80:
        return True, f"implausible claimed experience: {sum(years)} total years"
    return False, ""

# ---------------------------------------------------------------------------
# Scoring components
# ---------------------------------------------------------------------------

def _text(candidate: dict) -> str:
    parts = []
    for v in candidate.values():
        if isinstance(v, str):
            parts.append(v)
        elif isinstance(v, list):
            parts.extend(str(x) for x in v)
        elif isinstance(v, dict):
            parts.extend(str(x) for x in v.values())
    return " ".join(parts).lower()


def score_skill(text: str) -> float:
    hits = sum(1 for kw in SKILL_KEYWORDS if kw in text)
    max_useful = 40
    return min(math.log1p(hits) / math.log1p(max_useful), 1.0)


def score_experience(text: str) -> float:
    title_score = 0.0
    for kw, weight in EXPERIENCE_KEYWORDS.items():
        if kw in text:
            title_score = max(title_score, weight / 6.0)
    years = [int(m) for m in _YR_PATTERN.findall(text)]
    yr_score = 0.0
    if years:
        best_yr = min(max(years), 25)
        yr_score = best_yr / 25.0
    return min((title_score * 0.4 + yr_score * 0.6), 1.0)


def score_education(text: str) -> float:
    best = 0.0
    for kw, val in EDUCATION_LEVELS.items():
        if kw in text:
            best = max(best, val)
    return best


def score_activity(candidate: dict, current_year: int) -> float:
    all_text = _text(candidate)
    year_mentions = [
        int(y) for y in re.findall(r"\b(20[0-2]\d|19[89]\d)\b", all_text)
    ]
    if not year_mentions:
        return 0.3
    most_recent = max(year_mentions)
    age = max(current_year - most_recent, 0)
    return ACTIVITY_RECENCY_YEARS.get(age, 0.10)


def score_diversity(text: str) -> float:
    touched = sum(
        1 for domain_set in DIVERSITY_DOMAINS
        if any(kw in text for kw in domain_set)
    )
    return touched / len(DIVERSITY_DOMAINS)


def behavioral_multiplier(candidate: dict, text: str) -> float:
    mult = 1.0
    if any(x in text for x in ["github.com", "gitlab.com", "bitbucket"]):
        mult += 0.08
    if any(x in text for x in ["publication", "arxiv", "patent", "paper", "conference"]):
        mult += 0.10
    if any(x in text for x in ["certified", "certification", "aws certified", "gcp certified"]):
        mult += 0.05
    if "open source" in text or "contributor" in text:
        mult += 0.05
    if any(x in text for x in ["portfolio", "personal project", "side project"]):
        mult += 0.04
    if "employment gap" in text or "career break" in text:
        mult -= 0.05
    if len(text) < 100:
        mult -= 0.10
    return max(BEH_MIN, min(BEH_MAX, mult))


# ---------------------------------------------------------------------------
# Core scoring — returns (score, components_dict) for --explain support
# ---------------------------------------------------------------------------

def score_candidate_detailed(candidate: dict, current_year: int,
                              weights: dict) -> dict:
    """
    Returns a dict with all component scores, the multiplier, and final score.
    Used by both normal scoring and --explain mode.
    """
    text = _text(candidate)

    s_skill = score_skill(text)
    s_exp   = score_experience(text)
    s_edu   = score_education(text)
    s_act   = score_activity(candidate, current_year)
    s_div   = score_diversity(text)
    mult    = behavioral_multiplier(candidate, text)

    weighted = (
        weights["skill"]      * s_skill +
        weights["experience"] * s_exp   +
        weights["education"]  * s_edu   +
        weights["activity"]   * s_act   +
        weights["diversity"]  * s_div
    )
    final = round(min(max(weighted * mult, 0.0), 1.0), 6)

    return {
        "skill"      : round(s_skill, 6),
        "experience" : round(s_exp, 6),
        "education"  : round(s_edu, 6),
        "activity"   : round(s_act, 6),
        "diversity"  : round(s_div, 6),
        "beh_mult"   : round(mult, 4),
        "raw_score"  : round(weighted, 6),
        "final_score": final,
    }


def score_candidate(candidate: dict, current_year: int, weights: dict) -> float:
    return score_candidate_detailed(candidate, current_year, weights)["final_score"]


# ---------------------------------------------------------------------------
# Multiprocessing worker
# ---------------------------------------------------------------------------

# Module-level globals set by pool initializer (avoids pickling large objects)
_CURRENT_YEAR = None
_WEIGHTS      = None

def _pool_init(current_year: int, weights: dict) -> None:
    global _CURRENT_YEAR, _WEIGHTS
    _CURRENT_YEAR = current_year
    _WEIGHTS      = weights


def _score_chunk(chunk: list) -> list:
    """Score a list of (lineno, candidate) pairs. Called in worker processes."""
    results = []
    for lineno, candidate in chunk:
        cid = (
            candidate.get("candidate_id")
            or candidate.get("id")
            or candidate.get("_id")
            or str(lineno)
        )
        flat_text = _text(candidate)
        hp, hp_reason = is_honeypot(flat_text)
        if hp:
            results.append({
                "candidate_id": str(cid),
                "score"       : 0.0,
                "is_honeypot" : True,
                "hp_reason"   : hp_reason,
                "components"  : None,
            })
        else:
            det = score_candidate_detailed(candidate, _CURRENT_YEAR, _WEIGHTS)
            results.append({
                "candidate_id": str(cid),
                "score"       : det["final_score"],
                "is_honeypot" : False,
                "hp_reason"   : "",
                "components"  : det,
            })
    return results


# ---------------------------------------------------------------------------
# Weight normalisation helper
# ---------------------------------------------------------------------------

def build_weights(args: argparse.Namespace) -> dict:
    """
    Override default weights with any user-supplied --w-* flags.
    Re-normalises so they always sum exactly to 1.0.
    """
    w = dict(DEFAULT_WEIGHTS)
    overrides = {
        "skill"      : args.w_skill,
        "experience" : args.w_exp,
        "education"  : args.w_edu,
        "activity"   : args.w_act,
        "diversity"  : args.w_div,
    }
    for k, v in overrides.items():
        if v is not None:
            w[k] = v

    total = sum(w.values())
    if abs(total - 1.0) > 1e-6:
        print(f"[INFO] Weights sum to {total:.4f} — renormalising to 1.0")
        w = {k: v / total for k, v in w.items()}

    return w


def print_weights(weights: dict) -> None:
    print("[INFO] Component weights:")
    for k, v in weights.items():
        print(f"         {k:<12} {v:.4f}")


# ---------------------------------------------------------------------------
# --explain printer
# ---------------------------------------------------------------------------

def print_explanation(rank_pos: int, row: dict) -> None:
    comp = row.get("components") or {}
    weights = row.get("weights", DEFAULT_WEIGHTS)
    cid = row["candidate_id"]
    sep = "-" * 52

    print(f"\n  Rank #{rank_pos}  candidate_id: {cid}")
    print(f"  {sep}")
    print(f"  {'Component':<14} {'Score':>8}  {'Weight':>7}  {'Contrib':>8}")
    print(f"  {sep}")
    for component in ["skill", "experience", "education", "activity", "diversity"]:
        sc  = comp.get(component, 0.0)
        wt  = weights.get(component, DEFAULT_WEIGHTS[component])
        con = sc * wt
        print(f"  {component:<14} {sc:>8.6f}  {wt:>7.4f}  {con:>8.6f}")
    print(f"  {sep}")
    print(f"  {'raw_score':<14} {comp.get('raw_score', 0.0):>8.6f}")
    print(f"  {'beh_mult':<14} {comp.get('beh_mult', 1.0):>8.4f}")
    print(f"  {'final_score':<14} {row['score']:>8.6f}")
    print(f"  {sep}")


# ---------------------------------------------------------------------------
# I/O helpers
# ---------------------------------------------------------------------------

def open_input(path: Path):
    name = path.name.lower()
    if name.endswith(".jsonl.gz") or name.endswith(".json.gz"):
        return gzip.open(path, "rt", encoding="utf-8")
    return open(path, "r", encoding="utf-8")


def iter_candidates(path: Path):
    with open_input(path) as fh:
        for lineno, raw in enumerate(fh, start=1):
            raw = raw.strip()
            if not raw:
                continue
            try:
                obj = json.loads(raw)
            except json.JSONDecodeError as exc:
                print(f"  [WARN] line {lineno}: invalid JSON -- {exc}", file=sys.stderr)
                continue
            yield lineno, obj


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Team Cipher candidate ranking pipeline.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    p.add_argument("--candidates", required=True, type=Path,
                   help="Path to candidates JSONL or JSONL.GZ file.")
    p.add_argument("--out", required=True, type=Path,
                   help="Output CSV file path.")
    p.add_argument("--top", type=int, default=TOP_N,
                   help=f"Number of top candidates to write (default: {TOP_N}).")
    p.add_argument("--year", type=int, default=None,
                   help="Override 'current year' for activity scoring.")
    # Multiprocessing
    p.add_argument("--workers", type=int, default=1,
                   help="Number of parallel worker processes (default: 1).")
    # Explain
    p.add_argument("--explain", action="store_true",
                   help="Print per-candidate score breakdown for top candidates.")
    p.add_argument("--explain-n", type=int, default=10,
                   help="How many top candidates to explain (default: 10). Use 0 for all.")
    # Weight overrides
    p.add_argument("--w-skill", type=float, default=None,
                   help=f"Skill component weight (default: {DEFAULT_WEIGHTS['skill']}).")
    p.add_argument("--w-exp", type=float, default=None,
                   help=f"Experience component weight (default: {DEFAULT_WEIGHTS['experience']}).")
    p.add_argument("--w-edu", type=float, default=None,
                   help=f"Education component weight (default: {DEFAULT_WEIGHTS['education']}).")
    p.add_argument("--w-act", type=float, default=None,
                   help=f"Activity component weight (default: {DEFAULT_WEIGHTS['activity']}).")
    p.add_argument("--w-div", type=float, default=None,
                   help=f"Diversity component weight (default: {DEFAULT_WEIGHTS['diversity']}).")
    return p.parse_args()


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    args = parse_args()

    if not args.candidates.exists():
        sys.exit(f"[ERROR] Candidates file not found: {args.candidates}")

    current_year = args.year or time.localtime().tm_year
    top_n        = args.top
    weights      = build_weights(args)
    n_workers    = max(1, args.workers)

    print(f"[INFO] Input    : {args.candidates}")
    print(f"[INFO] Output   : {args.out}")
    print(f"[INFO] Top-N    : {top_n}")
    print(f"[INFO] Year     : {current_year}")
    print(f"[INFO] Workers  : {n_workers}")
    print_weights(weights)
    print()

    # -----------------------------------------------------------------------
    # Read all candidates into chunks
    # -----------------------------------------------------------------------
    all_pairs  = []
    bad_json   = 0
    t_start    = time.perf_counter()

    with open_input(args.candidates) as fh:
        for lineno, raw in enumerate(fh, start=1):
            raw = raw.strip()
            if not raw:
                continue
            try:
                obj = json.loads(raw)
            except json.JSONDecodeError:
                bad_json += 1
                continue

            all_pairs.append((lineno, obj))

            if lineno % PROGRESS_INTERVAL == 0:
                elapsed = time.perf_counter() - t_start
                rate = lineno / max(elapsed, 1e-9)
                print(
                    f"  [PROGRESS] {lineno:>10,} candidates read "
                    f"({rate:,.0f}/s) -- {elapsed:.1f}s elapsed"
                )

    total_read = len(all_pairs)
    print(f"\n[INFO] Read {total_read:,} candidates ({bad_json} bad JSON lines skipped)")

    # -----------------------------------------------------------------------
    # Score — parallel or single-process
    # -----------------------------------------------------------------------
    chunks = [
        all_pairs[i : i + CHUNK_SIZE]
        for i in range(0, len(all_pairs), CHUNK_SIZE)
    ]

    results    = []
    honeypots  = 0

    t_score = time.perf_counter()

    if n_workers > 1:
        print(f"[INFO] Scoring with {n_workers} worker processes ...")
        with multiprocessing.Pool(
            processes=n_workers,
            initializer=_pool_init,
            initargs=(current_year, weights),
        ) as pool:
            for chunk_results in pool.imap_unordered(_score_chunk, chunks):
                for r in chunk_results:
                    if r["is_honeypot"]:
                        honeypots += 1
                    results.append(r)
    else:
        # Single-process path — initialise globals directly
        _pool_init(current_year, weights)
        for chunk in chunks:
            for r in _score_chunk(chunk):
                if r["is_honeypot"]:
                    honeypots += 1
                results.append(r)

    score_elapsed = time.perf_counter() - t_score
    print(f"[INFO] Scoring complete in {score_elapsed:.2f}s")

    # -----------------------------------------------------------------------
    # Sort: score DESC, candidate_id ASC (tie-break)
    # -----------------------------------------------------------------------
    results.sort(key=lambda r: (-r["score"], r["candidate_id"]))
    top = results[:top_n]

    # Attach weights to each row for --explain
    for r in top:
        r["weights"] = weights

    # -----------------------------------------------------------------------
    # Write CSV
    # -----------------------------------------------------------------------
    args.out.parent.mkdir(parents=True, exist_ok=True)
    with open(args.out, "w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(
            fh,
            fieldnames=["rank", "candidate_id", "score", "is_honeypot", "hp_reason"],
        )
        writer.writeheader()
        for rank_pos, row in enumerate(top, start=1):
            writer.writerow({
                "rank"         : rank_pos,
                "candidate_id" : row["candidate_id"],
                "score"        : row["score"],
                "is_honeypot"  : row["is_honeypot"],
                "hp_reason"    : row["hp_reason"],
            })

    # -----------------------------------------------------------------------
    # --explain output
    # -----------------------------------------------------------------------
    if args.explain:
        explain_n = args.explain_n if args.explain_n > 0 else len(top)
        print(f"\n{'='*56}")
        print(f"  SCORE BREAKDOWN (top {min(explain_n, len(top))} candidates)")
        print(f"{'='*56}")
        for rank_pos, row in enumerate(top[:explain_n], start=1):
            print_explanation(rank_pos, row)

    # -----------------------------------------------------------------------
    # Final stats
    # -----------------------------------------------------------------------
    non_hp_top    = [r for r in top if not r["is_honeypot"]]
    scores_in_top = [r["score"] for r in top]
    total_elapsed = time.perf_counter() - t_start

    print()
    print("=" * 62)
    print("  FINAL STATS")
    print("=" * 62)
    print(f"  Total candidates processed : {total_read:,}")
    print(f"  Honeypots detected         : {honeypots:,}")
    print(f"  Rows written to CSV        : {len(top)} (+ 1 header)")
    if scores_in_top:
        print(f"  Score range of top-{top_n}      : "
              f"{min(scores_in_top):.6f} to {max(scores_in_top):.6f}")
    print(f"  Non-honeypot in top-{top_n}     : {len(non_hp_top)}")
    print(f"  Total wall time            : {total_elapsed:.2f}s")
    print(f"  Output file                : {args.out.resolve()}")
    print("=" * 62)


if __name__ == "__main__":
    main()
